### ISSUE TITLE
[SOLVED] Add coverage for negative numbers and values over 95

### ISSUE THREAD

**Issue by MilanGrujicic** [MilanGrujicic/Password-Generator#1]
When inserting negative numbers, the following error message is displayed:

```
Traceback (most recent call last):
  File "main_CLI.py", line 19, in <module>
    password = ''.join(random.sample(random_string, lenght))
  File "/usr/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```
The same happens when inserting a value higher than 95

**Comment by MilanGrujicic** [comment]
Addressed. Added following nested try catch block:
```
    try:
        try:
            lenght = int(userInput.get())
        except ValueError:
            resultLabel.configure(
                text="Input cannot be string nor symbol\nPlease insert value betwixt 1 and 95")
        else:
            generatePasswordButtonClicked(lenght)
    except ValueError:
        resultLabel.configure(
            text="Input cannot be less than 0 nor greater than 95\nPlease insert value betwixt 1 and 95")

```
